spring:
  datasource:
    url: jdbc:mysql://172.30.1.244:3306/hy_demo?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: atech
    password: atech1221!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: error
